### ISSUE TITLE
uap-ref-impl needs update on npm

### ISSUE THREAD

**Issue by commenthol** [ua-parser/uap-ref-impl#6]
The current version on npm is v0.1.0
```
$ npm info uap-ref-impl | grep version:
  version: '0.1.0',
```
The present is v0.2.0.
Can you please perform a `npm publish`?
Thanks

**Comment by jkevinburton** [comment]
+1

**Comment by commenthol** [comment]
ping...

**Comment by tobie** [comment]
Fixed: https://www.npmjs.com/package/uap-ref-impl
